import 'dart:async';

import 'package:flutter/material.dart';
import 'package:random_name_generator/random_name_generator.dart';
import 'date_ext.dart';
import 'occupation.dart';
import 'person.dart';

class AppState with ChangeNotifier {
  final _baseDate = DateTime(1920, 2, 12);

  AppState() {
    _people.addAll(_generatePeople());
    _dataUpdater();
  }
  //

  final rows = 5;

  final _people = <Person>[];
  List<Person> get people => [..._people];
  void deletePerson(String uuid) {
    _people.removeWhere((person) {
      if (person.uuid == uuid) {
        debugPrint("delete: ${person.fullName}");
        return true;
      }
      return false;
    });
    notifyListeners();
  }

  void addPerson() {
    final person = _generateNewPerson();
    _people.add(person);
    debugPrint("add: ${person.fullName}");
    notifyListeners();
  }

  final _randomNames = RandomNames(Zone.us);

  Person _generateNewPerson() {
    final firstName = _randomNames.name();
    final surname = _randomNames.surname();
    final birthday = _baseDate.getRandomDateUpTo();
    final occupation = Occupation.randomJob();
    final hasDog = firstName.startsWith('A');
    return Person(
      birthday: birthday,
      firstName: firstName,
      job: occupation,
      surname: surname,
      hasDog: hasDog,
    );
  }

  List<Person> _generatePeople() =>
      List.generate(rows, (row) => _generateNewPerson());

  // Simulate data being updated in the background, e.g. via the responses to a polling API request

  final _maxAutoGeneratedUsers = 20;

  void _dataUpdater() {
    Timer.periodic(Duration(seconds: 5), (timer) {
      if (_people.length < _maxAutoGeneratedUsers) {
        addPerson();
      } else {
        debugPrint("Purging excess people...");
        while (_people.length > 10) {
          deletePerson(_people.last.id);
        }
      }
    });
  }
}
